### ISSUE TITLE
Error in sxcompute_isac_avg.py", line 114, in compute_average_noctf     frc = fsc(fft(sumavg), fft(sumctf2)) UnboundLocalError: local variable 'sumavg' referenced before assignment

### ISSUE THREAD

**Issue by dallakyan** [cryoem/eman2#183]
I've looked at the code and this seems to be a bug. I'm coping complete Traceback  below. Please let me know if you have questions or need more information. Thank you.

mpirun -np 12 sxcompute_isac_avg.py --stack='start.hdf' --isac_dir='Class2D4' --output_dir='Class2D4/beautify2d_s' --radius=62 --noctf --pixel_size=1.62
2018-02-23_11:27:01 => Postprocessing ISAC 2D averages starts
2018-02-23_11:27:01 => Executed successfully:  mkdir Class2D4/beautify2d_s
Class2D4
 we don't get pixel size value
Traceback (most recent call last):
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 114, in compute_average_noctf
    frc = fsc(fft(sumavg), fft(sumctf2))
UnboundLocalError: local variable 'sumavg' referenced before assignment
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
Shutdown complete, exiting
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 110, in compute_average_noctf
    tmp = cosinemask(rot_shift2D(mlist[im], alpha, sx, sy, mr), radius)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 1011, in rot_shift2D
    if  mirror: img.process_inplace("xform.mirror", {"axis":'x'})
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 111, in compute_average_noctf
    tmp = fft(tmp)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 416, in fft
    return e.do_fft()
Traceback (most recent call last):
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 114, in compute_average_noctf
    frc = fsc(fft(sumavg), fft(sumctf2))
UnboundLocalError: local variable 'sumavg' referenced before assignment
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 110, in compute_average_noctf
    tmp = cosinemask(rot_shift2D(mlist[im], alpha, sx, sy, mr), radius)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 1010, in rot_shift2D
    img = img.rot_scale_trans2D_background(angle, sx, sy, scale)
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 110, in compute_average_noctf
    tmp = cosinemask(rot_shift2D(mlist[im], alpha, sx, sy, mr), radius)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/morphology.py", line 1364, in cosinemask
    return  Util.cosinemask(im, radius, cosine_width, bckg, s)
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 110, in compute_average_noctf
    tmp = cosinemask(rot_shift2D(mlist[im], alpha, sx, sy, mr), radius)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 1010, in rot_shift2D
    img = img.rot_scale_trans2D_background(angle, sx, sy, scale)
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 110, in compute_average_noctf
    tmp = cosinemask(rot_shift2D(mlist[im], alpha, sx, sy, mr), radius)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/morphology.py", line 1364, in cosinemask
    return  Util.cosinemask(im, radius, cosine_width, bckg, s)
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 111, in compute_average_noctf
    tmp = fft(tmp)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 416, in fft
    return e.do_fft()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 111, in compute_average_noctf
    tmp = fft(tmp)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 416, in fft
    return e.do_fft()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 111, in compute_average_noctf
    tmp = fft(tmp)
  File "/usr/local/EMAN2-SPHIRE/lib/python2.7/site-packages/fundamentals.py", line 416, in fft
    return e.do_fft()
Traceback (most recent call last):
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 550, in <module>
    main()
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 447, in main
    if Tracker["constants"]["noctf"]: ini_avg, frc = compute_average_noctf(mlist, Tracker["constants"]["radius"])
  File "/usr/local/EMAN2-SPHIRE/bin/sxcompute_isac_avg.py", line 114, in compute_average_noctf
    frc = fsc(fft(sumavg), fft(sumctf2))
UnboundLocalError: local variable 'sumavg' referenced before assignment
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[3037,1],3]
  Exit code:    1

**Comment by mstabrin** [comment]
Thank you for reporting!
It should be fixed in the current master branch.

**Comment by dallakyan** [comment]
Thank you much Markus. Used the current master branch and it worked. I appreciate your work.
