### ISSUE TITLE
traceback running e2projectmanager.py

### ISSUE THREAD

**Issue by dougbevan** [cryoem/eman2#258]
Hello.

We're having some issues with eman2 2.22 on a new system, CentOS 7.

As a user, trying to run e2projectmanager.py results in:

-bash-4.2$ e2projectmanager.py
Traceback (most recent call last):
  File "/opt/cryoem/EMAN2_2.22/lib/python2.7/site-packages/EMAN2jsondb.py", line 572, in open_db
    try : ret=JSDict(path)
  File "/opt/cryoem/EMAN2_2.22/lib/python2.7/site-packages/EMAN2jsondb.py", line 643, in __init__
    self.sync()
  File "/opt/cryoem/EMAN2_2.22/lib/python2.7/site-packages/EMAN2jsondb.py", line 693, in sync
    except: raise Exception("Error: Unable to open {} for writing".format(self.normpath))
Exception: Error: Unable to open /executor/info/project.json for writing
===========================
Traceback (most recent call last):
  File "/opt/cryoem/EMAN2_2.22/bin/e2projectmanager.py", line 2134, in <module>
    pm = EMProjectManager()
  File "/opt/cryoem/EMAN2_2.22/bin/e2projectmanager.py", line 67, in __init__
    self.loadPMdb()
  File "/opt/cryoem/EMAN2_2.22/bin/e2projectmanager.py", line 124, in loadPMdb
    self.pm_projects_db = js_open_dict("info/project.json")
  File "/opt/cryoem/EMAN2_2.22/lib/python2.7/site-packages/EMAN2jsondb.py", line 78, in js_open_dict
    return JSDict.open_db(url)
  File "/opt/cryoem/EMAN2_2.22/lib/python2.7/site-packages/EMAN2jsondb.py", line 577, in open_db
    raise Exception("Unable to open "+path)
Exception: Unable to open info/project.json

However, I am able to run it normally as root.  I have checked permissions, but can't seem to find an issue there.  Any assistance is appreciated.

**Comment by sludtke42** [comment]
It looks like you are trying to run e2projectmanager from a folder called /executor ?  This program must be run from a "project folder" (you create an empty folder and cd into it), and the user must have write permission to it. 

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by dougbevan** [comment]
This makes sense and was an oversight when testing with other users.  Thank you for pointing it out.  Appreciate the assistance.
