### ISSUE TITLE
ImportError: No module named past.utils

### ISSUE THREAD

**Issue by zhixuanli** [cryoem/eman2#365]
I have installed EMAN2 following this page: https://blake.bcm.edu/emanwiki/EMAN2/Install/BinaryInstallAnaconda/2.22

I'm working on my PC, the system is Ubuntu 16.04.

When I'm trying to test, the `python e2version.py` works fine. Here's the output:
```
EMAN 2.22 final (GITHUB: 2018-08-20 20:32 - commit: f4f3952 )
Your EMAN2 is running on: Linux-4.8.0-36-generic-x86_64-with-debian-stretch-sid 4.8.0-36-generic
Your Python version is: 2.7.15
```

And when running `e2speedtest.py`, the above error occurred:
```
ImportError: No module named past.utils
```

Could you give me some advice? 

Thank you so much!!!

**Comment by zhixuanli** [comment]
I find that an `activate` file is under the `~/EMAN2/bin` folder.
So I run `source ~/EMAN2/bin/activate` to activate this environment. But it failed.

Here's the output:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/oliver/EMAN2/lib/python2.7/site-packages/conda/cli/main.py", line 98, in main
        return activator_main()
      File "/home/oliver/EMAN2/lib/python2.7/site-packages/conda/activate.py", line 632, in main
        print(activator.execute(), end='')
      File "/home/oliver/EMAN2/lib/python2.7/site-packages/conda/activate.py", line 166, in execute
        return getattr(self, self.command)()
      File "/home/oliver/EMAN2/lib/python2.7/site-packages/conda/activate.py", line 152, in activate
        return self._finalize(self._yield_commands(self.build_activate(self.env_name_or_prefix)),
      File "/home/oliver/EMAN2/lib/python2.7/site-packages/conda/activate.py", line 250, in build_activate
        assert 0 <= old_conda_shlvl <= max_shlvl
    AssertionError

`$ /home/oliver/EMAN2/bin/conda shell.posix activate`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
        CONDA_DEFAULT_ENV=cell
                CONDA_EXE=/home/oliver/anaconda3/bin/conda
             CONDA_PREFIX=/home/oliver/anaconda3/envs/cell
           CONDA_PREFIX_1=/home/oliver/anaconda3
           CONDA_PREFIX_2=/home/oliver/anaconda3/envs/pytorch
    CONDA_PROMPT_MODIFIER=(cell)
         CONDA_PYTHON_EXE=/home/oliver/anaconda3/bin/python
               CONDA_ROOT=/home/oliver/EMAN2
              CONDA_SHLVL=3
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
          LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64:
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/oliver/EMAN2/bin:/usr/local/cuda/bin:/usr/local/cuda/bin:/home/o
                          liver/anaconda3/envs/cell/bin:/home/oliver/anaconda3/condabin:/home/ol
                          iver/bin:/home/oliver/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/s
                          bin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : /home/oliver/anaconda3/envs/cell
    active env location : /home/oliver/anaconda3/envs/cell
            shell level : 3
       user config file : /home/oliver/.condarc
 populated config files : /home/oliver/.condarc
          conda version : 4.5.10
    conda-build version : 3.13.0
         python version : 2.7.15.final.0
       base environment : /home/oliver/EMAN2  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/oliver/EMAN2/pkgs
                          /home/oliver/.conda/pkgs
       envs directories : /home/oliver/EMAN2/envs
                          /home/oliver/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.10 requests/2.19.1 CPython/2.7.15 Linux/4.8.0-36-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

So this means that the installation progress was failed.

What should I do now?

Thank you!

**Comment by shadowwalkersb** [comment]
It looks like you have activated multiple environments on top of each other: cell, base and pytorch. And, you have two different anaconda installations in `PATH`: EMAN2 and anaconda3. EMAN2 installation should be the only installation in `PATH` for it to work. It should, also, be possible to activate the EMAN2 installation through the main anaconda installation, but that would require some advanced conda/anaconda knowledge which would be challenging for us to properly document in the EMAN2 wiki.

**Comment by zhixuanli** [comment]
Thank you!! @shadowwalkersb
