### ISSUE TITLE
2.99.57 Version ctest test failed

### ISSUE THREAD

**Issue by simon28li** [cryoem/eman2#574]
hi When I was testing version 2.99.57, there was an error in progs. It was an error fragment:
```
[root@localhost spack-build-xxwzugl]#ctest
Test project /home/stage/root/spack-stage-eman2-2.99.57-xxwzuglpxb35u7p3cmxflnc7c6shtffm/spack-build-xxwzugl
    Start 1: py-compile
1/6 Test #1: py-compile .......................   Passed    0.13 sec
    Start 2: imports
2/6 Test #2: imports ..........................   Passed    0.30 sec
    Start 3: test-EMAN2DIR
3/6 Test #3: test-EMAN2DIR ....................   Passed    2.47 sec
    Start 4: nose-tests
4/6 Test #4: nose-tests .......................   Passed   16.37 sec
    Start 5: progs
5/6 Test #5: progs ............................***Failed   30.81 sec
    Start 6: test-eer
6/6 Test #6: test-eer .........................   Passed    0.01 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) =  50.10 sec

The following tests FAILED:
          5 - progs (Failed)
Errors while running CTest

Running: e2spt_boxer.py -h
/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 45, in <module>
    from ._check_build import check_build  # noqa
ImportError: /home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/eman2-2.99.57-xxwzuglpxb35u7p3cmxflnc7c6shtffm/bin/e2gmm_rigidbody.py", line 24, in <module>
    from e2gmm_refine_new import *
  File "/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/eman2-2.99.57-xxwzuglpxb35u7p3cmxflnc7c6shtffm/bin/e2gmm_refine_new.py", line 5, in <module>
    from sklearn.decomposition import PCA
  File "/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/sklearn/__init__.py", line 79, in <module>
    from . import (
  File "/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 47, in <module>
    raise_build_error(e)
  File "/home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: /home/spack/opt/spack/linux-openeuler20-aarch64/gcc-7.3.0/python-3.8.8-ktpokql7mq2pnofbqca2ujsfpiztrzrv/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
```

**Comment by sludtke42** [comment]
Not clear if this will be a real problem with using EMAN2 or not. This is an error in libgomp/numpy in your environment, nothing directly related to EMAN2. If you google this issue, you can find some discussion of the underlying problem. Looks like you are running on a Mac?  Using the updated conda-forge based installtion instructions, I haven’t seen any issues so far on my own Mac (with EMAN2).

**Comment by simon28li** [comment]
What is the recommended version of NumPy and whether it is earlier than 1.20.0? I found another error.
```
File "/home/spack/opt/spack/linux-openeuler22-aarch64/gcc-10.3.1/python-3.8.8-kk3hqlp6z5u7ycjvcfcaqugvlbfxjxo6/lib/python3.8/site-packages/PIL/_typing.py", line 10, in <module>
5:     NumpyArray = npt.NDArray[Any]
5: AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```

**Comment by sludtke42** [comment]
Please see the note at the top of the source installation page regarding dependencies (https://eman2.org/Install/SourceInstall). I'm currently using 1.26.4.

**Comment by sludtke42** [comment]
That program is not yet complete (actually, I'm not sure if it's even more than a tweaked copy of an older program right now). All of the "e3*" programs are still under development. It is possible that there will be occasional accidental commits with syntax errors, etc. 

We do not suggest that end users run manual precompilation of the entire python codebase. It's completely pointless and can reveal "problems" which aren't actually problems. There is a much longer list of things that we need/want to get done than we have developers to deal with. Problems which don't impact usability are at the bottom of the "to fix" pile.
